name: Kanban App CI/CD


on:
  push:
    branches: [ main ]  
  pull_request:
    branches: [ main ]  


env:
  
  MONGODB_URI_TEST: ${{ secrets.MONGODB_URI_TEST }}
  JWT_SECRET: ${{ secrets.JWT_SECRET }}
  RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
  RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
  
  FRONTEND_URL: http://localhost:3000
  


jobs:
  test:  
    runs-on: ubuntu-latest  

    steps:
      
      - name: Get code from repository
        uses: actions/checkout@v2

      
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          cache: 'npm'

      
      - name: Install dependencies
        run: npm ci  

      
      - name: Run tests
        run: npm test
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          RECAPTCHA_SECRET_KEY: ${{ secrets.RECAPTCHA_SECRET_KEY }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          FRONTEND_URL: http://localhost:3000

  
  deploy:
    needs: test  
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'  

    steps:
      - name: Deploy to Render
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        run: |
          curl -X POST "https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys" \
          -H "Authorization: Bearer $RENDER_API_KEY"